### ISSUE TITLE
Pool ID

### ISSUE THREAD

**Issue by liptonj** [bdwilson/waterguru-api#1]
you have your pool id hard coded in the app.  How did you get the pool id from water guru

**Comment by bdwilson** [comment]
Go to /api/wg and you'll see waterBodyId

**Comment by liptonj** [comment]
But is the information below static?
        pool_id = "us-west-2_icsnuWQWw"
	identity_pool_id = "us-west-2:691e3287-5776-40f2-a502-759de65a8f1c"
	client_id = "7pk5du7fitqb419oabb3r92lni"

**Comment by bdwilson** [comment]
It is static. This is what Waterguru is using for their IAM management.
