### ISSUE TITLE
Feature Request: Home Assistant Integration

### ISSUE THREAD

**Issue by teek541** [bdwilson/waterguru-api#4]
Can you make this a Home Assistant Integration rather than a docker for those of us who aren't running HA in a docker?

**Comment by bdwilson** [comment]
Sorry, I don’t use HA. Happy to take contributions from someone who does. Either way, you need  the docker piece as the intermediary between WaterGuru and your home automation system, unless HA native supports python.

**Comment by teek541** [comment]
https://www.home-assistant.io/docs/backend/

It's built on Python 3

;-)

I'm learning Python and some other coding languages as I dive into HA.  I've always been a SQL/VB (I know, it's not a REAL programming language) kind of guy.  Broadening my horizons. lol

**Comment by soupman98** [comment]
> Can you make this a Home Assistant Integration rather than a docker for those of us who aren't running HA in a docker?

+1 on this ask. Just starting my GitHub, Python, HomeAssistant journey!

**Comment by bdwilson** [comment]
Sorry folks, currently not in the cards.

**Comment by soupman98** [comment]
Thanks

**Comment by bdwilson** [comment]
Looks like this has been done https://github.com/dwradcliffe/home-assistant-waterguru
