### ISSUE TITLE
Incorrect Cassette Days Remaining

### ISSUE THREAD

**Issue by WorldOfMaze** [bdwilson/waterguru-api#5]
I am using the Home Assistance integration for WaterGuru which is reading data from this API.I just replaced the cassette in my WaterGuru.  The sensor is showing `2` which, when I look in the app is 2 months.  Is there a way to correct this so the sensor is always days or, alternatively, add an attribute to the sensor to indicate if the unit of measure is days or months?

Thanks.

**Comment by bdwilson** [comment]
What model do you have? Sense or Sense 2?

**Comment by WorldOfMaze** [comment]
The original Sense that only measures pH and FC.

**Comment by WorldOfMaze** [comment]
Today the says 8 weeks and the HA Integration simply returns the 8.  Are you passing the unit of measure (days, weeks, months) as part of the Cassette Days Remaining?

**Comment by bdwilson** [comment]
I didn't write the HA integration, perhaps ask whomever did that? I assume they are trying to compute it to days vs using the returned value. I'm just dumping the json as it is returned from WaterGuru. 

podId":13696,"refillables":[{"viewType":"RefillableView","status":"GREEN","type":"LAB","color":"#23B8DC","label":"Cassette","maxAmount":"174","amountLeft":"78","unit":"pad","timeLeftText":"26 days left","pctLeft":45.0,"pctLeftDec":"45","urgent":false,"refillTime":"2024-04-27T12:59:55.577Z"},

![image](https://github.com/bdwilson/waterguru-api/assets/317946/5d9e3aa4-0672-4a55-9bd7-043079dc1539)

**Comment by WorldOfMaze** [comment]
I have also opened an issue for the HA integration.  He says the integration is just a wrapper around your API so I, apparently incorrectly, assumed the issue was with your API.

Thanks for the feedback.
