### ISSUE TITLE
[DISREGARD]

### ISSUE THREAD

**Issue by OtisPresley** [bdwilson/waterguru-api#8]
Opened in error

**Comment by bdwilson** [comment]
Is this not an issue with Home Assistant? I don't have anything to do with the HA integration.

**Comment by OtisPresley** [comment]
@bdwilson, thank you! I had thought this was opened under the WaterGuru integration area.

**Comment by OtisPresley** [comment]
@bdwilson Thanks! I will open in the correct project.
